# Дважды транспонированная матрица равна исходной матрице:

In [2]:
import numpy as np

In [5]:
>>> A = np.random.randint(-20, 100, (3, 3))
>>> print(A)
>>> R = (A.T).T
>>> print(R)

[[ 2  5 28]
 [29 53 94]
 [-5 63 71]]
[[ 2  5 28]
 [29 53 94]
 [-5 63 71]]


# Транспонирование суммы матриц равно сумме транспонированных матриц:

In [6]:
>>> A = np.random.randint(-20, 100, (2, 3))
>>> B = np.random.randint(-20, 100, (2, 3))
>>> L = (A + B).T
>>> R = A.T + B.T
>>> print(L)
>>> print(R)

[[102  50]
 [ 97 130]
 [122  60]]
[[102  50]
 [ 97 130]
 [122  60]]


# Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [7]:
>>> A = np.random.randint(-20, 100, (2, 2))
>>> B = np.random.randint(-20, 100, (2, 2))
>>> L = (A.dot(B)).T
>>> R = (B.T).dot(A.T)
>>> print(L)
>>> print(R)

[[ 727 2809]
 [ 560  335]]
[[ 727 2809]
 [ 560  335]]


# Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [8]:
>>> A = np.random.randint(-20, 100, (3, 2))
>>> k = 3
>>> L = (k * A).T
>>> R = k * (A.T)
>>> print(L)
>>> print(R)

[[282  93 132]
 [ -9 -36 183]]
[[282  93 132]
 [ -9 -36 183]]


# Определители исходной и транспонированной матрицы совпадают:

In [9]:
>>> A = np.random.randint(-20, 100, (5, 5))
>>> A_det = np.linalg.det(A)
>>> A_T_det = np.linalg.det(A.T)
>>> print(format(A_det, '.9g'))
>>> print(format(A_T_det, '.9g'))

125000169
125000169


# Произведение единицы и любой заданной матрицы равно заданной матрице:

In [10]:
>>> A = np.random.randint(5, 100, (2, 2))
>>> L = 1 * A
>>> R = A
>>> print(L)
>>> print(R)

[[93 59]
 [88  5]]
[[93 59]
 [88  5]]


# Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [12]:
>>> A = np.random.randint(-20, 100, (2, 2))
>>> Z = np.matrix('0 0; 0 0')
>>> L = 0 * A
>>> R = Z
>>> print(L)
>>> print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


# Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [13]:
>>> A = np.random.randint(-20, 100, (4, 7))
>>> p = 2
>>> q = 3
>>> L = (p + q) * A
>>> R = p * A + q * A
>>> print(L)
>>> print(R)

[[145 465 250  80 415 230 400]
 [140 425 460 495 305 465 110]
 [430 425 440 450 225 -35 205]
 [190 130 315 225 165 365 485]]
[[145 465 250  80 415 230 400]
 [140 425 460 495 305 465 110]
 [430 425 440 450 225 -35 205]
 [190 130 315 225 165 365 485]]


# Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [14]:
>>> A = np.random.randint(-20, 100, (2, 7))
>>> p = 2
>>> q = 3
>>> L = (p * q) * A
>>> R = p * (q * A)
>>> print(L)
>>> print(R)

[[  60  474  330  378  210   54  258]
 [ 426   72  432  384 -108  -84  246]]
[[  60  474  330  378  210   54  258]
 [ 426   72  432  384 -108  -84  246]]


# Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [16]:
>>> A = np.random.randint(50, 100, (5, 3))
>>> B = np.random.randint(30, 100, (5, 3))
>>> k = 3
>>> L = k * (A + B)
>>> R = k * A + k * B
>>> print(L)
>>> print(R)

[[459 378 348]
 [321 393 483]
 [342 447 351]
 [351 366 435]
 [474 333 396]]
[[459 378 348]
 [321 393 483]
 [342 447 351]
 [351 366 435]
 [474 333 396]]


# Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [17]:
>>> A = np.random.randint(-10, 100, (3, 3))
>>> B = np.random.randint(-19, 100, (3, 3))
>>> L = A + B
>>> R = B + A
>>> print(L)
>>> print(R)

[[120 150  51]
 [ 44  66  72]
 [153  37 112]]
[[120 150  51]
 [ 44  66  72]
 [153  37 112]]


# Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [18]:
>>> A = np.random.randint(-20, 50, (5, 2))
>>> B = np.random.randint(0, 50, (5, 2))
>>> C = np.random.randint(-20, 50, (5, 2))
>>> L = A + (B + C)
>>> R = (A + B) + C
>>> print(L)
>>> print(R)

[[97  9]
 [78 88]
 [21 96]
 [76 84]
 [36 56]]
[[97  9]
 [78 88]
 [21 96]
 [76 84]
 [36 56]]


# Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей:

In [19]:
>>> A = np.random.randint(0, 50, (2, 2))
>>> Z = np.matrix('0 0; 0 0')
>>> L = A + (-1)*A
>>> print(L)
>>> print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


# Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [20]:
>>> A = np.random.randint(-7, 50, (3, 3))
>>> B = np.random.randint(-7, 50, (3, 3))
>>> C = np.random.randint(-7, 50, (3, 3))
>>> L = A.dot(B.dot(C))
>>> R = (A.dot(B)).dot(C)
>>> print(L)
>>> print(R)

[[121648  27334  63100]
 [ 51026  11158  24370]
 [ 56020  12568  28552]]
[[121648  27334  63100]
 [ 51026  11158  24370]
 [ 56020  12568  28552]]


# Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [21]:
>>> A = np.random.randint(-20, 50, (2, 2))
>>> B = np.random.randint(-20, 50, (2, 2))
>>> C = np.random.randint(-20, 50, (2, 2))
>>> L = A.dot(B + C)
>>> R = A.dot(B) + A.dot(C)
>>> print(L)
>>> print(R)

[[ 500  700]
 [-292 -308]]
[[ 500  700]
 [-292 -308]]


# Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [22]:
>>> A = np.random.randint(-20, 100, (5, 5))
>>> B = np.random.randint(-20, 100, (5, 5))
>>> L = A.dot(B)
>>> R = B.dot(A)
>>> print(L)
>>> print(R)

[[ 6528  9242  7567   423 11170]
 [13833 16291  3156  7395 17196]
 [ 3329  9679  3463  4272  9356]
 [ 6638 11207  7364   564  9548]
 [10496 15344  7517  2385 14334]]
[[ 9328  5956 10972  9496 12654]
 [ 9567  8068  4806  7618  9016]
 [ 9679 10040  5783  8621 13522]
 [ 7435  4072 14676  6350 11828]
 [10045  6686 11107  6751 11651]]


# Произведение заданной матрицы на единичную равно исходной матрице:

In [23]:
>>> A = np.random.randint(-20, 100, (2, 2))
>>> E = np.matrix('1 0; 0 1')
>>> L = E.dot(A)
>>> R = A.dot(E)
>>> print(L)
>>> print(R)
>>> print(A)

[[44 47]
 [76 55]]
[[44 47]
 [76 55]]
[[44 47]
 [76 55]]


# Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [24]:
>>> A = np.random.randint(50, 100, (4, 4))
>>> Z = np.zeros((4, 4))
>>> L = Z.dot(A)
>>> R = A.dot(Z)
>>> print(L)
>>> print(R)
>>> print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Определитель матрицы остается неизменным при ее транспонировании:

In [26]:
>>> A = np.random.randint(-6, 100, (5, 5))
>>> print(A)
>>> print(A.T)
>>> det_A = round(np.linalg.det(A), 3)
>>> det_A_t = round(np.linalg.det(A.T), 3)
>>> print(det_A)
>>> print(det_A_t)

[[67 60 80 83 45]
 [-6 69 60 47 51]
 [91 18 45 48 87]
 [11 89 34  5 13]
 [10 13 42  9 86]]
[[67 -6 91 11 10]
 [60 69 18 89 13]
 [80 60 45 34 42]
 [83 47 48  5  9]
 [45 51 87 13 86]]
701067603.0
701067603.0


# Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [28]:
>>> A = np.matrix('243 22 1512 4242; 0 0 0 0; 32 7 9 4; 42 1214 455 522')
>>> print(A)
>>> np.linalg.det(A)

[[ 243   22 1512 4242]
 [   0    0    0    0]
 [  32    7    9    4]
 [  42 1214  455  522]]


0.0

# При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [34]:
>>> A = np.matrix('-90 134; 1141 -1')
>>> print(A)
>>> B = np.matrix('1141 -1; -90 134')
>>> print(B)
>>> print(round(np.linalg.det(A), 3))
>>> round(np.linalg.det(B), 3)

[[ -90  134]
 [1141   -1]]
[[1141   -1]
 [ -90  134]]
-152804.0


152804.0

# Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [35]:
>>> A = np.matrix('-4 -1 2 453; -4 -1 2 363; 442 22 11 32; 442 22 11 32')
>>> print(A)
>>> np.linalg.det(A)

[[ -4  -1   2 453]
 [ -4  -1   2 363]
 [442  22  11  32]
 [442  22  11  32]]


0.0

# Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [37]:
>>> A = np.random.randint(-15, 90, (7, 7))
>>> print(A)
>>> k = 2
>>> B = A.copy()
>>> B[2, :] = k * B[2, :]
>>> print(B)
>>> det_A = round(np.linalg.det(A), 3)
>>> det_B = round(np.linalg.det(B), 3)
>>> print(det_A * k)
>>> det_B

[[ 49  40  70  26  60  -6  25]
 [ -3  68  88  83  39  -1  62]
 [ 23 -11  54   6 -11 -10  -7]
 [ 48  55  76  20  -2 -11  52]
 [ 84  44  15  65  39  20  15]
 [ 73  42  66  78  76  41  62]
 [ 61  80  31   4  77  64   4]]
[[ 49  40  70  26  60  -6  25]
 [ -3  68  88  83  39  -1  62]
 [ 46 -22 108  12 -22 -20 -14]
 [ 48  55  76  20  -2 -11  52]
 [ 84  44  15  65  39  20  15]
 [ 73  42  66  78  76  41  62]
 [ 61  80  31   4  77  64   4]]
-15279913856789.982


-15279913856790.01

# Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [39]:
>>> A = np.random.randint(-15, 90, (4, 4))
>>> B = np.random.randint(-15, 90, (4, 4))
>>> C = A.copy()
>>> C[1, :] += B[1, :]
>>> print(C)
>>> print(A)
>>> print(B)
>>> print(round(np.linalg.det(C), 3))
>>> round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

[[83 20 70 72]
 [75 33 35 83]
 [ 2 72 61 11]
 [72 62 18  6]]
[[83 20 70 72]
 [75 16 29 77]
 [ 2 72 61 11]
 [72 62 18  6]]
[[-5  0 68 85]
 [ 0 17  6  6]
 [60 23 87 74]
 [12 43 17 51]]
-22590248.0


-20810569.0

# Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [40]:
>>> A = np.random.randint(7, 90, (3, 3))
>>> k = 2
>>> B = A.copy()
>>> B[1, :] = B[1, :] + k * B[0, :]
>>> print(A)
>>> print(B)
>>> print(round(np.linalg.det(A), 3))
>>> round(np.linalg.det(B), 3)

[[49 35 21]
 [24 60 54]
 [82 40 77]]
[[ 49  35  21]
 [122 130  96]
 [ 82  40  77]]
127680.0


127680.0

# Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [41]:
>>> A = np.matrix('535 -241 22; 1 24 -1; 526 5 1')
>>> print(A)
>>> k = 2
>>> A[1, :] = A[0, :] + k * A[2, :]
>>> round(np.linalg.det(A), 3)

[[ 535 -241   22]
 [   1   24   -1]
 [ 526    5    1]]


0.0

# Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [42]:
>>> A = np.random.randint(-87, 90, (6, 6))
>>> print(A)
>>> k = 2
>>> A[1, :] = k * A[0, :]
>>> print(A)
>>> round(np.linalg.det(A), 3)

[[ 32  35 -79 -13  -2  24]
 [-25  56 -10 -84  42 -26]
 [ 63 -61  -3  47 -86  85]
 [ 22 -43 -69  -2  57  34]
 [-54  -2  23 -56 -32   9]
 [-80  11  16 -87  84  -2]]
[[  32   35  -79  -13   -2   24]
 [  64   70 -158  -26   -4   48]
 [  63  -61   -3   47  -86   85]
 [  22  -43  -69   -2   57   34]
 [ -54   -2   23  -56  -32    9]
 [ -80   11   16  -87   84   -2]]


0.0

# Обратная матрица обратной матрицы есть исходная матрица:

In [44]:
>>> A = np.random.uniform(-87., 90., (4, 4))
>>> A_inv = np.linalg.inv(A)
>>> A_inv_inv = np.linalg.inv(A_inv)
>>> print(A)
>>> print(A_inv_inv)

[[-77.51297809  36.9903236   37.91831909 -57.66060159]
 [ -1.49275301  48.38315589  68.34564781  -5.42582336]
 [-71.295893   -56.50234838  47.53848087 -41.08487581]
 [ 69.18670277 -28.66419052 -14.3503396   51.63565556]]
[[-77.51297809  36.9903236   37.91831909 -57.66060159]
 [ -1.49275301  48.38315589  68.34564781  -5.42582336]
 [-71.295893   -56.50234838  47.53848087 -41.08487581]
 [ 69.18670277 -28.66419052 -14.3503396   51.63565556]]


# Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [46]:
>>> A = np.random.uniform(-7., 90., (3, 3))
>>> L = np.linalg.inv(A.T)
>>> R = (np.linalg.inv(A)).T
>>> print(L)
>>> print(R)

[[-0.01803632  0.07557992 -0.06375944]
 [ 0.05061056 -0.06537994  0.01589703]
 [-0.0238444  -0.03909121  0.10282702]]
[[-0.01803632  0.07557992 -0.06375944]
 [ 0.05061056 -0.06537994  0.01589703]
 [-0.0238444  -0.03909121  0.10282702]]


# Обратная матрица произведения матриц равна произведению обратных матриц:

In [47]:
>>> A = np.random.uniform(3., 90., (3, 3))
>>> B = np.random.uniform(50., 90., (3, 3))
>>> L = np.linalg.inv(A.dot(B))
>>> R = np.linalg.inv(B).dot(np.linalg.inv(A))
>>> print(L)
>>> print(R)

[[ 0.00539561 -0.007298    0.00118221]
 [-0.00441834  0.00759437 -0.00227042]
 [-0.00096821 -0.00051423  0.0013198 ]]
[[ 0.00539561 -0.007298    0.00118221]
 [-0.00441834  0.00759437 -0.00227042]
 [-0.00096821 -0.00051423  0.0013198 ]]
